<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />

    <Compile Include="Domain.fs" />
    <Compile Include="Infrastructure.fs" />
    <Compile Include="Apis.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Giraffe" Version="8.2.0" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
  </ItemGroup>

</Project>
